### PR TITLE
Increase MEMFILE_MAX to 1Mb

### LINKED ISSUE #7: Increase max size of request
See https://github.com/Valloric/ycmd/issues/306 for detailed explanation, but we need to hack the `MEMFILE_MAX` in `bottle` to support the same size files as `ycmd`.

### PR DESCRIPTION
**Pull request by vheon**
Fixes #7

[Review on Reviewable](https://reviewable.io/reviews/vheon/jedihttp/8)

### CODE REVIEW

**Comment by vheon** [comment]
@homu r+

**Comment by puremourning** [comment]
err yeah. shoulda said you also need `import bottle`

sorry 'bout that :/

**Comment by vheon** [comment]
> err yeah. shoulda said you also need import bottle
> 
> sorry 'bout that :/

Don't worry. I thought that I already had it, instead I was importing specific things from it.

**Comment by vheon** [comment]
@homu r+

**Pull request merged**
