### PR TITLE
Support standard Python packaging via setup.py

### LINKED ISSUE #17: Provide setup script
I'm not too familiar with Python development, but a `setup.py` script to install a Python program on the system seems commonplace.

As I'd like to package this or a Linux distro, such a script would be very convenient.

### PR DESCRIPTION
**Pull request by yan12125**
Fixes #17

The name `jedihttp-main.py` is just an example. Any name other than `jedihttp.py` is fine.

---

This change is [Reviewable](https://reviewable.io/reviews/vheon/jedihttp/19)

### CODE REVIEW

**Comment by vheon** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

_[setup.py, line 32 [r1]](https://reviewable.io:443/reviews/vheon/jedihttp/19#-KM165l8v99Cm2MpZKSG:-KM165l8v99Cm2MpZKSH:-2100003383) ([raw file](https://github.com/vheon/jedihttp/blob/13f9635d04313a214a854c1f20a0e10d2044ff18/setup.py#L32)):_

> ``` Python
> 
>     scripts=[ 'jedihttp-main.py' ],
>     install_requires=dependencies,
> ```

Wouldn't this mean that if you install this package with the setuptools you will get this from some kind of repo instead of using the submodule that I have in the `vendor` directory?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vheon/jedihttp/19)_

**Comment by yan12125** [comment]
_[setup.py, line 32 [r1]](https://reviewable.io:443/reviews/vheon/jedihttp/19#-KM165l8v99Cm2MpZKSG:-KM320qC0dvdBEgoSpq0:1667041917) ([raw file](https://github.com/vheon/jedihttp/blob/13f9635d04313a214a854c1f20a0e10d2044ff18/setup.py#L32)):_
<details><summary>

<i>Previously, vheon (Andrea Cedraro) wrote…</i></summary>



> Wouldn't this mean that if you install this package with the setuptools you will get this from some kind of repo instead of using the submodule that I have in the `vendor` directory?
> </details>
> Yes. Are you worrying about out-dated dependencies? How about 1f44c366f23c9b59f17e15f4641fcb9045cdc093? Force all dependencies to have the latest version.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vheon/jedihttp/19)_

**Comment by vheon** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

_[setup.py, line 32 [r1]](https://reviewable.io:443/reviews/vheon/jedihttp/19#-KM165l8v99Cm2MpZKSG:-KM5NKwfgTC9rNxucOKi:-929398282) ([raw file](https://github.com/vheon/jedihttp/blob/13f9635d04313a214a854c1f20a0e10d2044ff18/setup.py#L32)):_
<details><summary>

<i>Previously, yan12125 (Yen Chi Hsuan) wrote…</i></summary>



> Yes. Are you worrying about out-dated dependencies? How about 1f44c366f23c9b59f17e15f4641fcb9045cdc093? Force all dependencies to have the latest version.
> </details>
> No, I'm worried that a user could run using version of a dependency that wasn't tested. This is the reason I used the submodule in the first place.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vheon/jedihttp/19)_

**Comment by yan12125** [comment]
_[setup.py, line 32 [r1]](https://reviewable.io:443/reviews/vheon/jedihttp/19#-KM165l8v99Cm2MpZKSG:-KM5RTfEEhZ42JWg0nDd:-935263920) ([raw file](https://github.com/vheon/jedihttp/blob/13f9635d04313a214a854c1f20a0e10d2044ff18/setup.py#L32)):_
<details><summary>

<i>Previously, vheon (Andrea Cedraro) wrote…</i></summary>



> No, I'm worried that a user could run using version of a dependency that wasn't tested. This is the reason I used the submodule in the first place.
> </details>
> By https://github.com/vheon/JediHTTP/tree/master/vendor, submodules are stick with stable releases, while bottle and waitress are out-dated. If all dependencies are up-to-date, using == and >= in setup.py should yield the same result. Here I use >= just for the case that a dependency gets a new version while JediHTTP is not updated yet. If you don't like users to have a different dependency version than the one in submodules, I can change >= to ==.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vheon/jedihttp/19)_

**Comment by vheon** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

_[setup.py, line 32 [r1]](https://reviewable.io:443/reviews/vheon/jedihttp/19#-KM165l8v99Cm2MpZKSG:-KM5VmjOd2fERlOeMDCF:1444777445) ([raw file](https://github.com/vheon/jedihttp/blob/13f9635d04313a214a854c1f20a0e10d2044ff18/setup.py#L32)):_
<details><summary>

<i>Previously, yan12125 (Yen Chi Hsuan) wrote…</i></summary>



> By https://github.com/vheon/JediHTTP/tree/master/vendor, submodules are stick with stable releases, while bottle and waitress are out-dated. If all dependencies are up-to-date, using == and >= in setup.py should yield the same result. Here I use >= just for the case that a dependency gets a new version while JediHTTP is not updated yet. If you don't like users to have a different dependency version than the one in submodules, I can change >= to ==.
> </details>
> can't setuptools just download the submodule as well? :confused: 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vheon/jedihttp/19)_

**Comment by yan12125** [comment]
_[setup.py, line 32 [r1]](https://reviewable.io:443/reviews/vheon/jedihttp/19#-KM165l8v99Cm2MpZKSG:-KM5XvMpuVFXdcn6ZnSc:-1212138096) ([raw file](https://github.com/vheon/jedihttp/blob/13f9635d04313a214a854c1f20a0e10d2044ff18/setup.py#L32)):_
<details><summary>

<i>Previously, vheon (Andrea Cedraro) wrote…</i></summary>



> can't setuptools just download the submodule as well? :confused: 
> </details>
> One of the central philosophy in my recent work on YCM related projects is that they should be able to use system provided libraries, so that the overall installation time is reduced. For Python packages, `setup.py` is an easy way to simplify the whole process. If you think submodules are the only acceptable approach, please close this pull request. A `setup.py` is not necessary if submodules are used.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vheon/jedihttp/19)_

**Comment by vheon** [comment]
As our discussion in the review I guess I'm going to close this. I've really appreciated the fact that you decided to spend some time on this and I'm sorry that I've make you "waste" your time though. Thanks again for the contribution.

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

_[setup.py, line 32 [r1]](https://reviewable.io:443/reviews/vheon/jedihttp/19#-KM165l8v99Cm2MpZKSG:-KM61nxnyg6f8-8EUTBR:-168910647) ([raw file](https://github.com/vheon/jedihttp/blob/13f9635d04313a214a854c1f20a0e10d2044ff18/setup.py#L32)):_

> One of the central philosophy in my recent work on YCM related projects is that they should be able to use system provided libraries

Which is the opposite of what we want with YCM and now that YCM has grown we regret the fact that options like `--system-boost` or `--system-libclan` exists in the first place because we have to handle problems which are dependable on the environment and not easily reproducible; plus we have to maintain code to "support" unsupported platform.

> A setup.py is not necessary if submodules are used.

That was my first thought but I saw people asking for the `setup.py` and I don't know if someone want to use this outside of `ycmd`.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vheon/jedihttp/19#-:-KM63xLBRrHuhjZebLlD:1414215347)_

**Pull request closed without merging**
