### PR TITLE
[READY] Enable coverage

### PR DESCRIPTION
**Pull request by micbou**
Use [codecov](https://codecov.io/) for coverage reports. Fix thread coverage by updating Waitress dependency to 0.8.10 (see [this commit message](https://github.com/Valloric/ycmd/commit/d233603727817f1c976d6800675cb3e79356411d)).

---
This change is [Reviewable](https://reviewable.io/reviews/vheon/jedihttp/41)

### CODE REVIEW

**Comment by micbou** [comment]
Took me some time but the OS X builds are now successfully uploading the coverage reports. The issue was that the `install.sh` script was not sourced and so it wasn't using the Python where coverage.py was installed when trying to upload the report.

Also, I removed the virtualenv part (and the `run.sh` script) since tox is already creating a virtual environment.

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vheon/jedihttp/41#-:-Kwpps6LzJhYkU_hwv1a:b-25yyy4)*

**Comment by vheon** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[jedihttp/__main__.py, line 11 at r1](https://reviewable.io:443/reviews/vheon/jedihttp/41#-KwslW5rTjF0gVGmzoxb:-KwslW5sphnr24D0RGYf:b-shzqrn) ([raw file](https://github.com/vheon/jedihttp/blob/bfba349aa0400e8262ca6f8d88c64055c1cff3b9/jedihttp/__main__.py#L11)):*
> ```Python
> # distributed under the License is distributed on an "AS IS" BASIS,
> # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
> # See the License for the specific language governing permissions and
> ```

Isn't this renamed file a breaking change? What benefit it will bring, other than it looks more Pythonic? I'm not saying that I'm against it, just checking :confused: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vheon/jedihttp/41)*

**Comment by micbou** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[jedihttp/__main__.py, line 11 at r1](https://reviewable.io:443/reviews/vheon/jedihttp/41#-KwslW5rTjF0gVGmzoxb:-Kwt7TAUW-nlqkSMnUUK:bs8bej6) ([raw file](https://github.com/vheon/jedihttp/blob/bfba349aa0400e8262ca6f8d88c64055c1cff3b9/jedihttp/__main__.py#L11)):*
<details><summary><i>Previously, vheon (Andrea Cedraro) wrote…</i></summary><blockquote>

Isn't this renamed file a breaking change? What benefit it will bring, other than it looks more Pythonic? I'm not saying that I'm against it, just checking :confused: 
</blockquote></details>

I couldn't find a way to configure nosetests coverage without renaming this file.  The issue is that nosetests considers `jedihttp/__init__.py` and `jedihttp.py` to be the same file and thus it sees `jedihttp.py` as an empty file. With all files put in the `jedihttp` directory, it's just a matter of adding the `--cover-module=jedihttp` option to the `nosetests` call. Also, as you said, it's a more standard way of structuring a Python package.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vheon/jedihttp/41)*

**Comment by vheon** [comment]
:lgtm: @zzbot r+

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vheon/jedihttp/41#-:-KxA-HsOeHye_J16Ggno:by5ago3)*

**Pull request merged**
