### PR TITLE
Get ready to be packaged for a linux distro

### PR DESCRIPTION
**Pull request by cbosdo**
The most controversial point here is to rename the jedihttp.py into jedihttp-server... but otherwise we are getting such an error:

    Traceback (most recent call last):
      File "/usr/bin/jedihttp.py", line 15, in <module>
        from jedihttp import utils
      File "/usr/bin/jedihttp.py", line 15, in <module>
        from jedihttp import utils
    ImportError: cannot import name utils

openSUSE package can be temporarily found [on this OBS repository](https://build.opensuse.org/package/show/home:cbosdonnat:branches:home:hurricanehernandez:youcompleteme/python-jedihttp). It will hopefully move towards openSUSE:Factory soon

---
This change is [Reviewable](https://reviewable.io/reviews/vheon/jedihttp/34)

### CODE REVIEW

**Comment by vheon** [comment]
First of all thanks for the PR!

But as explained in other issues https://github.com/vheon/JediHTTP/issues/17 and https://github.com/vheon/JediHTTP/pull/19 the big issue that I see here is that you're not using the git submodules that I've put into the `vendor` directory. Now I know this is not the usual package system used in Python but I didn't know better when I started this. Anyway that are the version for which JediHTTP is tested against and that are the one JediHTTP should use.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vheon/jedihttp/34#-:-KkC7f6i9EixNKzF6kl-:b-53eajm)*

**Comment by cbosdo** [comment]
@vheon I don't blame your for the git submodules, nor do I want to prevent you from working this way. This is only to allow to build without the vendor. As a packager I just can't packaged the vendor folder and I am required to use the system libraries instead. Obviously if someone reports a bug due to the versions mismatch, we openSUSE community packager will handle it (and possibly fix it) before you see the issue.

As for the `setup.py`, people don't have to use it... I just wanted to share the one I use to package JediHTTP in a RPM. I'm not expert enough in distutils to handle both cases with and without vendor folder.

**Comment by vheon** [comment]
Reviewed 1 of 5 files at r1.
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[jedihttp/utils.py, line 21 at r1](https://reviewable.io:443/reviews/vheon/jedihttp/34#-KkCgF7pRT1BYTiv238c:-KkCgF7pRT1BYTiv238d:b83azv3) ([raw file](https://github.com/vheon/jedihttp/blob/77faa830dd9766eaa829d911ca891fb72b5657cf/jedihttp/utils.py#L21)):*
> ```Python
>   vendor_folder = os.path.join( os.path.dirname( __file__ ), '..', 'vendor' )
> 
>   if os.path.exists(vendor_folder):
> ```

Why is this here? I mean, even if you clone the repo without calling `git submodules update --init` the directory would still be there and inside it there would be the `waitress`, `argparse`, `bottle` and `jedi` directory :confused: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vheon/jedihttp/34)*

**Comment by vheon** [comment]
@micbou you are for sure more experienced than me with Python, so if you want to say something it would be much appreciated 👍

**Comment by cbosdo** [comment]
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[jedihttp/utils.py, line 21 at r1](https://reviewable.io:443/reviews/vheon/jedihttp/34#-KkCgF7pRT1BYTiv238c:-KkF10zOTB4Qv9iNic5C:b-pdkx9h) ([raw file](https://github.com/vheon/jedihttp/blob/77faa830dd9766eaa829d911ca891fb72b5657cf/jedihttp/utils.py#L21)):*
<details><summary><i>Previously, vheon (Andrea Cedraro) wrote…</i></summary><blockquote>

Why is this here? I mean, even if you clone the repo without calling `git submodules update --init` the directory would still be there and inside it there would be the `waitress`, `argparse`, `bottle` and `jedi` directory :confused: 
</blockquote></details>

This is targeting the installed case.  When installed in a system, the `jedihttp` directory is moved to the `site-packages` folder (for example `/usr/lib/python2.7/site-packages`). The `vendor` folder however is not installed on the system since we have the dependencies already installed in the python path.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vheon/jedihttp/34)*

**Comment by cbosdo** [comment]
@zzbot rebased now.

**Comment by yan12125** [comment]
Since #41, adding packaging support is much simpler. ```jedihttp.py``` is renamed to ```jedihttp/__main__.py``` following common Python packaging practices, so there's no need to rename files around. Simply using ```console_scripts``` is enough. And changes in ```tests``` are no longer necessary, either. My packaging scripts for Arch Linux at https://aur.archlinux.org/cgit/aur.git/tree/?h=python-jedihttp-git might help opensuse people, too.

**Comment by micbou** [comment]
See PR https://github.com/Valloric/ycmd/pull/1028.

**Pull request closed without merging**
