### PR TITLE
Add support for finding references

### PR DESCRIPTION
**Pull request by ptrv**
[Review on Reviewable](https://reviewable.io/reviews/vheon/jedihttp/5)

### CODE REVIEW

**Comment by vheon** [comment]
Thanks for the PR! I'm thinking of JediHTTP as a thin wrapper around jedi so I would prefer if the handle is called `/usages` as the jedi method itself. Plus I don't know if I would like the returned json object to have the key `definitions` for a handle called `/usages` or even `/findreferences`.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vheon/jedihttp/5#-:-K7XIxs7hbhyAYQ1HCr9:187585229)_

**Comment by ptrv** [comment]
Ok, I'll rename the request to `/usages`.

From the jedi api documentation for `usages()`:

> Return classes.Definition objects, which contain all names that point to the definition of the name under the cursor.

It returns the same object as from `goto_assignments` or `goto_definitions` so I don't see why it shouldn't return definitions.

I could change the key to `usages` or something else but I don't really see a benefit. What do you think?

**Comment by vheon** [comment]
> Ok, I'll rename the request to /usages.

Thanks.

> From the jedi api documentation for usages():
> 
> > Return classes.Definition objects, which contain all names that point to the definition of the name under the cursor.
> 
> It returns the same object as from goto_assignments or goto_definitions so I don't see why it shouldn't return definitions.
> 
> I could change the key to usages or something else but I don't really see a benefit. What do you think?

Yes, I went and read the doc myself and you're right. At this point though would you mind renaming `_FormatGoToDefinitions` to just `_FormatDefinitions`?

**Comment by ptrv** [comment]
@vheon Renamed to `usages` and also `_FormatDefinitions`

**Comment by vheon** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[jedihttp/handlers.py, line 77 [r2]](https://reviewable.io:443/reviews/vheon/jedihttp/5#-K7XYX5QwriNEdaup2f_:-K7XYX5QwriNEdaup2fa:-1926926187) ([raw file](https://github.com/vheon/jedihttp/blob/9d913160a5e6b8fa1e12abd97cd13d60a83c9142/jedihttp/handlers.py#L77)):_
could you rename the method itself?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vheon/jedihttp/5)_

**Comment by ptrv** [comment]
_[jedihttp/handlers.py, line 77 [r2]](https://reviewable.io:443/reviews/vheon/jedihttp/5#-K7XYX5QwriNEdaup2f_:-K7XYz-YbpT2TtWtkWQ7:-771424729) ([raw file](https://github.com/vheon/jedihttp/blob/9d913160a5e6b8fa1e12abd97cd13d60a83c9142/jedihttp/handlers.py#L77)):_
Sure, I overlooked this.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vheon/jedihttp/5)_

**Comment by vheon** [comment]
Thanks! @homu r+

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vheon/jedihttp/5#-:-K7X_BtOMooHzNFKgqgW:1918001751)_

**Comment by ptrv** [comment]
Thanks!
I'll add the subcommand in `ycmd` and prepare the PR there.

**Comment by vheon** [comment]
@ptrv I already have a PR pending on `ycmd` regarding another feature. We could think about do it all at once.

**Comment by ptrv** [comment]
@vheon Here is what I have so far: https://github.com/Valloric/ycmd/compare/master...ptrv:python-find-usages-support
I don't mind doing the PR with your feature. Whatever is the easiest

**Comment by vheon** [comment]
@ptrv so you're basically done :+1:  Then send it, no problem :smiley:

**Pull request merged**
