### PR TITLE
[READY] Follow PEP8 code style

### PR DESCRIPTION
**Pull request by micbou**
Following [PEP8 code style](https://www.python.org/dev/peps/pep-0008/) requires some changes in `test_requirements.txt` and `tox.ini`:
 - add `pep8-naming` package to follow [PEP8 naming conventions](https://www.python.org/dev/peps/pep-0008/#naming-conventions);
 - add flake8 configuration to `tox.ini`: [only ignore E203 and E402](https://pycodestyle.readthedocs.io/en/latest/intro.html#error-codes). Adding whitespaces before `:` improves readability when defining dictionaries and moving all imports at the top of file is not possible because of packages bundling;
 - fix flake8 runs on Travis and AppVeyor (`py27-flake8` and `py36-flake8` through the `tox -e` command were running the tests instead of flake8).

---
This change is [Reviewable](https://reviewable.io/reviews/vheon/jedihttp/38)

### CODE REVIEW

**Comment by micbou** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tox.ini, line 7 at r1](https://reviewable.io:443/reviews/vheon/jedihttp/38#-Ku17PF5cce_9llKmdZv:-Ku17PF5cce_9llKmdZw:b-qwpilb) ([raw file](https://github.com/vheon/jedihttp/blob/464a2136793ed4d2d7e9d24a320d47019be04b99/tox.ini#L7)):*
> ```INI
> deps = -r{toxinidir}/test_requirements.txt
> commands =
>     nosetests -v {posargs}
> ```

This allows running specific tests e.g.
```sh
tox -e py36 jedihttp/tests/end_to_end_test.py
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vheon/jedihttp/38)*

**Comment by micbou** [comment]
That's it. The whole codebase is converted to PEP8. I recommend to review the changes in reviewable. Its diff algorithm is so much better than the GitHub one.

---

Reviewed 10 of 10 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[jedihttp/tests/utils.py, line 41 at r3](https://reviewable.io:443/reviews/vheon/jedihttp/38#-Ku9W_3w6ca_P6MIE-V3:-Ku9W_3xszGWXJBHquT3:bc1jq94) ([raw file](https://github.com/vheon/jedihttp/blob/a4afec54534299a973ba032e16c9b7a7c3f558d4/jedihttp/tests/utils.py#L41)):*
> ```Python
>   if OnWindows():
>     return os.path.abspath( '/Python33/python' )
>   else:
> ```

We don't need the `else` since we are returning in the `if`branch.

---

*[jedihttp/tests/utils.py, line 48 at r3](https://reviewable.io:443/reviews/vheon/jedihttp/38#-Ku9WcSrn-euJGzWMtF1:-Ku9WcSrn-euJGzWMtF2:bs4q9op) ([raw file](https://github.com/vheon/jedihttp/blob/a4afec54534299a973ba032e16c9b7a7c3f558d4/jedihttp/tests/utils.py#L48)):*
> ```Python
>   if sys.version_info < ( 3, 0 ) and 'CROSS_PYTHON_TESTS' in os.environ:
>     return python3()
>   else:
> ```

Ditto.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vheon/jedihttp/38#-:-Ku9ViKQkOo3M8xCazd1:btzzowm)*

**Comment by vheon** [comment]
Reviewed 1 of 2 files at r1, 7 of 10 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[tox.ini, line 22 at r3](https://reviewable.io:443/reviews/vheon/jedihttp/38#-KuC-ZNCl4rsi0zhHNrF:-KuC-ZNCl4rsi0zhHNrG:b-lizc7l) ([raw file](https://github.com/vheon/jedihttp/blob/647a1abc367bca0cbee63c4483fa0b39fc506ccd/tox.ini#L22)):*
> ```INI
>     flake8
> [flake8]
> ignore = E203, E402
> ```

Is there a particular reason we're ignoring `E203`?

---

*[jedihttp/handlers.py, line 142 at r3](https://reviewable.io:443/reviews/vheon/jedihttp/38#-KuC0aMjFu2HQl1fl6Ll:-KuC0aMjFu2HQl1fl6Lm:bel531u) ([raw file](https://github.com/vheon/jedihttp/blob/647a1abc367bca0cbee63c4483fa0b39fc506ccd/jedihttp/handlers.py#L142)):*
> ```Python
>     return {
>         'definitions': [{
>             'module_path'      : definition.module_path,
> ```

this looks like the only instance where we aligned the `:`, in other section of this PR are moved the other way. I would suggest to not align them and lose also the `ignore E203` in the flake8 config.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vheon/jedihttp/38)*

**Comment by micbou** [comment]
We now enforce `E203`.

---

Reviewed 2 of 3 files at r4.
Review status: 11 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[tox.ini, line 22 at r3](https://reviewable.io:443/reviews/vheon/jedihttp/38#-KuC-ZNCl4rsi0zhHNrF:-KuC2ejEiFH2ylNrEBl8:b3vkejp) ([raw file](https://github.com/vheon/jedihttp/blob/647a1abc367bca0cbee63c4483fa0b39fc506ccd/tox.ini#L22)):*
<details><summary><i>Previously, vheon (Andrea Cedraro) wrote…</i></summary><blockquote>

Is there a particular reason we're ignoring `E203`?
</blockquote></details>

I felt that aligning on `:` when defining dictionaries for readability was more important than following this rule.

---

*[jedihttp/handlers.py, line 142 at r3](https://reviewable.io:443/reviews/vheon/jedihttp/38#-KuC0aMjFu2HQl1fl6Ll:-KuC3TSkBDFgu49RvcHn:b-1pcsd1) ([raw file](https://github.com/vheon/jedihttp/blob/647a1abc367bca0cbee63c4483fa0b39fc506ccd/jedihttp/handlers.py#L142)):*
<details><summary><i>Previously, vheon (Andrea Cedraro) wrote…</i></summary><blockquote>

this looks like the only instance where we aligned the `:`, in other section of this PR are moved the other way. I would suggest to not align them and lose also the `ignore E203` in the flake8 config.
</blockquote></details>

There is also the dictionary in `_format_completions` but yes, it's not worth ignoring `E203`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vheon/jedihttp/38#-:-KuC4LjuBP9h7OevXMFf:b-7vcyk7)*

**Comment by vheon** [comment]
Reviewed 2 of 3 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[jedihttp/handlers.py, line 142 at r3](https://reviewable.io:443/reviews/vheon/jedihttp/38#-KuC0aMjFu2HQl1fl6Ll:-KuEUIl7ac0u5RIXqUmM:bxwcux3) ([raw file](https://github.com/vheon/jedihttp/blob/647a1abc367bca0cbee63c4483fa0b39fc506ccd/jedihttp/handlers.py#L142)):*
<details><summary><i>Previously, micbou wrote…</i></summary><blockquote>

There is also the dictionary in `_format_completions` but yes, it's not worth ignoring `E203`.
</blockquote></details>

we can put the spaces after the `:` if we want to align the dictionary

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vheon/jedihttp/38)*

**Comment by micbou** [comment]
Reviewed 1 of 3 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[jedihttp/handlers.py, line 142 at r3](https://reviewable.io:443/reviews/vheon/jedihttp/38#-KuC0aMjFu2HQl1fl6Ll:-KuEXo5vQ1BxeNfF_nk1:bhpoots) ([raw file](https://github.com/vheon/jedihttp/blob/647a1abc367bca0cbee63c4483fa0b39fc506ccd/jedihttp/handlers.py#L142)):*
<details><summary><i>Previously, vheon (Andrea Cedraro) wrote…</i></summary><blockquote>

we can put the spaces after the `:` if we want to align the dictionary
</blockquote></details>

In that case, we need to ignore `E241`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vheon/jedihttp/38)*

**Comment by vheon** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[jedihttp/handlers.py, line 142 at r3](https://reviewable.io:443/reviews/vheon/jedihttp/38#-KuC0aMjFu2HQl1fl6Ll:-KuFe2aJ9JFFRlzaAjFU:b-lphnrh) ([raw file](https://github.com/vheon/jedihttp/blob/647a1abc367bca0cbee63c4483fa0b39fc506ccd/jedihttp/handlers.py#L142)):*
<details><summary><i>Previously, micbou wrote…</i></summary><blockquote>

In that case, we need to ignore `E241`.
</blockquote></details>

I was reading http://pep8.readthedocs.io/en/release-1.7.x/intro.html and it didn't look like it :confused: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vheon/jedihttp/38)*

**Comment by micbou** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[jedihttp/handlers.py, line 142 at r3](https://reviewable.io:443/reviews/vheon/jedihttp/38#-KuC0aMjFu2HQl1fl6Ll:-KuFtD8qr4XbZDcQiBQ-:b-5me7pi) ([raw file](https://github.com/vheon/jedihttp/blob/647a1abc367bca0cbee63c4483fa0b39fc506ccd/jedihttp/handlers.py#L142)):*
<details><summary><i>Previously, vheon (Andrea Cedraro) wrote…</i></summary><blockquote>

I was reading http://pep8.readthedocs.io/en/release-1.7.x/intro.html and it didn't look like it :confused: 
</blockquote></details>

`E241` is ignored by default but not if we specify an ignore list. So, should we add `E241` then?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vheon/jedihttp/38)*

**Comment by vheon** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[jedihttp/handlers.py, line 142 at r3](https://reviewable.io:443/reviews/vheon/jedihttp/38#-KuC0aMjFu2HQl1fl6Ll:-KuLjIN3Zk4PmdaEaQuW:b-ueftqq) ([raw file](https://github.com/vheon/jedihttp/blob/647a1abc367bca0cbee63c4483fa0b39fc506ccd/jedihttp/handlers.py#L142)):*
<details><summary><i>Previously, micbou wrote…</i></summary><blockquote>

`E241` is ignored by default but not if we specify an ignore list. So, should we add `E241` then?
</blockquote></details>

At this point I think is down to personal preference but between the two I would prefer to ignore `E241`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vheon/jedihttp/38)*

**Comment by micbou** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[jedihttp/handlers.py, line 142 at r3](https://reviewable.io:443/reviews/vheon/jedihttp/38#-KuC0aMjFu2HQl1fl6Ll:-KuM85-gmNXvcfY1vQt6:b-6affyh) ([raw file](https://github.com/vheon/jedihttp/blob/647a1abc367bca0cbee63c4483fa0b39fc506ccd/jedihttp/handlers.py#L142)):*
<details><summary><i>Previously, vheon (Andrea Cedraro) wrote…</i></summary><blockquote>

At this point I think is down to personal preference but between the two I would prefer to ignore `E241`.
</blockquote></details>

Let's ignore `E241` then.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vheon/jedihttp/38)*

**Comment by vheon** [comment]
Thanks! :lgtm:  @zzbot r+

---

Reviewed 2 of 10 files at r2, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vheon/jedihttp/38#-:-KuQJph1D_2Qf4o4hFUn:b-g44kav)*

**Pull request merged**
